// printing definitions; file $incluso by macros

const
	GALATEO_PARM_SELECT_RECORDS = 'PARM_SELECT_RECORDS';		// query che seleziona i dati da stampare
	GALATEO_PARM_LO_KEY_SESSIONE = 'PARM_LO_KEY_SESSIONE';
	GALATEO_PARM_DT_ELABORAZIONE = 'PARM_DT_ELABORAZIONE';		// generica data di elaborazione

{$ifdef PRODUZIONE}
	PRODUZ_PARM_POSTAZIONE = 'PARM_POSTAZIONE';
	PRODUZ_PARM_OPERATORE = 'PARM_OPERATORE';
	PRODUZ_PARM_OPERATORI_ELENCO = 'PARM_OPERATORI';
	PRODUZ_PARM_BO_LAVORAZIONE_PRINCIPALE = 'PARM_BO_LAVORAZIONE_PRINCIPALE';
	PRODUZ_PARM_ID_PIANIFICAZIONE = 'PARM_ID_PIANIFICAZIONE';
{$endif PRODUZIONE}

{$ifdef TERMICO}
	REP_IMPIANTO = 'imp_term';		// prospetto di stampa impianto (non centrale)
{$endif TERMICO}

	PRINT_CAPTION_BASE = 'caption';
	PRINT_FONDOPAGINA_BASE = 'fondopagina';

	REP_ELENCO_MATERIALI = 'elenco_materiali';	// elenco articoli di bolle/ordini
	REP_ELENCO_MATERIALI_ACCORPATI = 'elenco_materiali_accorpati';

	PRINT_LABEL_PREFIX = 'TXT_';	// prefisso che identifica la corrispondente label
	PRINT_TOTAL_PREFIX = 'TOT_';	// prefisso che identifica il corrispondente totale

	// stampa archivio articoli composta dynamicamente --------------------------
	PRINT_ARKART_CODICE = 'CODICE';
	PRINT_ARKART_CODICE_PRIVATO = 'COD_PRIV';
	PRINT_ARKART_DESCRIZIONE_CORTA = 'DESCRIZIONE_CORTA';
	PRINT_ARKART_DESCRIZIONE_LUNGA = 'DESCRIZIONE_LUNGA';
	PRINT_ARKART_LISTINO_BASE = 'LISTINO_';

	PRINT_ARKART_CODICE_LISTINO_FORN_PRINC = TBL_ALWF_STR_LISTINO;
	PRINT_ARKART_LISTINO_FORN_PRINC = TBL_ALWF_CR_LISTINO_FORNITORE;
	PRINT_ARKART_SCONTO_FORN_PRINC = TBL_ALWF_STR_SCONTO_FORNITORE;
	PRINT_ARKART_SCONTATO_FORN_PRINC = TBL_ALWF_CR_SCONTATO_FORNITORE;
	PRINT_ARKART_DT_UPDATE_FORN_PRINC = 'ALF_DT_UPDATE';

	PRINT_ARKART_CODICE_LISTINO_CLI_PRINC = TBL_ALWC_STR_LISTINO;
	PRINT_ARKART_LISTINO_CLI_PRINC = TBL_ALWC_CR_LISTINO_CLIENTE;
	PRINT_ARKART_RICARICO_CLI_PRINC = TBL_ALWC_STR_RICARICO_CLIENTE;

	PRINT_ARKART_VALORE_GIACENZA = 'valore_giacenza';
	PRINT_ARKART_LISTINO_IN_OPERA = 'LISTINO_IN_OPERA';	// usa ricarico e costo mdo default

	PRINT_ARKART_CODICI = 'CODICE_';	// +zeri(i,2), il primo ha codice 02

	PRINT_ARKART_TEMPOPOSA = 'TEMPOPOSA';
	PRINT_ARKART_PESO = 'PESO';
	PRINT_ARKART_QTA_UM = 'UM';
	PRINT_ARKART_QTA_COMPLETA = 'QTA_FISICA_FISCALE';
	PRINT_ARKART_QTA_SOLO_FISICA = 'QTA_SOLO_FISICA';
	PRINT_ARKART_QTA_FISICA_TOT = 'QTA_FISICA_TOT';
	PRINT_ARKART_QTA_SOLO_FISCALE = 'QTA_SOLO_FISCALE';
	PRINT_ARKART_QTA_FISCALE_TOT = 'QTA_FISCALE_TOT';
//	PRINT_ARKART_SEZIONE_MAIN = 'PRINCIPALE';
	PRINT_ARKART_SEZIONE_DISTINTA_BASE = 'GB_DISTINTA_BASE';
	PRINT_ARKART_DB_COSTO = 'COSTO_DISTINTA_BASE';	// sezione GB_DISTINTA_BASE

	PRINT_ARKART_STR_MAGAZZINO_CAPTION = 'PARM_MAGAZZINO_CAPTION';
	PRINT_ARKART_PARM_FL_QTA_FP = 'PARM_FL_QTA_FP';
	PRINT_ARKART_PARM_FL_QTA_F = 'PARM_FL_QTA_F';
	PRINT_ARKART_PARM_FL_QTA_P = 'PARM_FL_QTA_P';

	// --------------------------------------------------------------------------

	// stampa pconti composta dynamicamente -------------------------------------
	PRINT_PCONTI_CODICE = 'CODICE';
	PRINT_PCONTI_DESCRIZIONE_UNITA = 'DESCRIZIONE_UNITA';
	PRINT_PCONTI_COGNOME = 'COGNOME';
	PRINT_PCONTI_NOME = 'NOME';
	PRINT_PCONTI_TIPOCONTO = 'TIPOCONTO';
	PRINT_PCONTI_CODICE_FISCALE = 'CODICE_FISCALE';
	PRINT_PCONTI_PARTITA_IVA = 'PARTITA_IVA';
	PRINT_PCONTI_CONDIZIONE_PAGAMENTO = 'CONDIZIONE_PAGAMENTO';
	PRINT_PCONTI_NOTE = 'NOTE';
	PRINT_PCONTI_WWW = 'WWW';
	PRINT_PCONTI_EMAIL = 'EMAIL';
	PRINT_PCONTI_REFERENTE = 'REFERENTE';
	PRINT_PCONTI_BANCA_UTENTE = 'BANCA_UTENTE';
	PRINT_PCONTI_BANCA_CLIFOR = 'BANCA_CLI_FOR';
	PRINT_PCONTI_AGENTE = 'AGENTE';
	PRINT_PCONTI_KM = 'KM';
	PRINT_PCONTI_RICERCA_LIBERA = 'RICERCA_LIBERA';
	PRINT_PCONTI_COSTO_INTERVENTO = 'COSTO_INTERVENTO';
	PRINT_PCONTI_CODICE_AGG_BASE = 'CODICE_';	// aggiungere la cifra (2 cifre) del codice
	PRINT_PCONTI_INDIRIZZI = 'INDIRIZZI';
	PRINT_PCONTI_PARM_BO_ONLY_INDIRIZZO_PRINCIPALE = 'PARM_BO_ONLY_INDIRIZZO_PRINCIPALE';
	PRINT_PCONTI_PARM_BO_TUTTI_GLI_INDIRIZZI = 'PARM_BO_TUTTI_GLI_INDIRIZZI';
	PRINT_PCONTI_PARM_BO_TELEFONI = 'PARM_BO_TELEFONI';
	PRINT_PCONTI_PARM_BO_INDIRIZZI_IMPIANTI = 'PARM_BO_INDIRIZZI_IMPIANTI';
	// rubrica
	PRINT_PCONTI_PARM_BO_CODICE = 'parm_bo_codice';
	PRINT_PCONTI_PARM_BO_IMPIANTI = 'parm_bo_impianti';
	PRINT_PCONTI_PARM_BO_PIVA = 'parm_bo_piva';
	PRINT_PCONTI_PARM_BO_CF = 'parm_bo_cf';
//	PRINT_PCONTI_PARM_BO_TIPOCONTO = 'parm_bo_tipoconto';
	PRINT_PCONTI_PARM_BO_WWW = 'parm_bo_www';
	PRINT_PCONTI_PARM_BO_EMAIL = 'parm_bo_email';
	PRINT_PCONTI_PARM_BO_REFERENTE = 'parm_bo_referente';
	// --------------------------------------------------------------------------

	PRINT_SECTION_MAIN = 'Principale';
	PRINT_SECTION_DETTAGLIO = 'Dettaglio';
	PRINT_SECTION_GROUP_BY_1 = 'GB_1';

	REP_DOTAZIONE_MAGAZZINO = 'dotazione_magazzino';

//	REP_AGENDA = 'agenda_elenco_chiamate';		// agenda con/senza interventi
	REP_AGENDA_INTERVENTI = 'agenda_elenco_interventi';	// solo interventi
	PRINT_AGENDA_DESCR_GRUPPO_CHIAMATE = 'DESCR_GRUPPO_CHIAMATE';

{$ifdef ELE}
	// parametri standard utilizzati nella stampa di ELE
	ELE_PRINT_PROJECT_PARM = 'str_project_parm';
	ELE_PRINT_CHAPTER_PARM = 'lo_key_chapter_parm';
	ELE_PRINT_CAPTION_PARM = 'str_titolo_stampa';
	ELE_PRINT_BO_PREZZI_BLANK = 'bo_prezzi_blank';
	ELE_PRINT_BO_DESCRIZIONE_LUNGA = 'PARM_bo_descrizione_lunga';
	{$ifdef DISTINTA_BASE} ELE_PRINT_BO_DESCRIZIONE_LUNGA_DB = 'PARM_bo_descrizione_lunga_DB'; {$endif}
	ELE_PRINT_LISTINO_BASE = 'PARM_listino_';	// + zeri(i,2), zero-based
//	ELE_PRINT_ORE_GIORNO = 'PARM_ore_giorno';		// quante ore ha un giorno?
	// ELE General Conditions Macro; macro utilizzabili nelle stampe di ELE
	ELE_GCM_NUMBER = 17;
	ELE_MACRO_CODICE						= 'CODICE_PROGETTO';
	ELE_MACRO_DT_PROGETTO				= 'DATA_PROGETTO';
	ELE_MACRO_DT_SCADENZA				= 'DATA_SCADENZA';
	ELE_MACRO_ID_CONGELATO				= 'ID_PROGETTO_CONGELATO';
	ELE_MACRO_PROGRESSIVO				= 'NUMERO_PROGRESSIVO';
	ELE_MACRO_DATA_INIZIO_LAVORI		= 'DATA_INIZIO_LAVORI';
	ELE_MACRO_DATA_CONSEGNA				= 'DATA_CONSEGNA';
	ELE_MACRO_CONDIZIONI_PAGAMENTO	= 'CONDIZIONI_PAGAMENTO';
	ELE_MACRO_TOTALE_CONCORDATO		= 'TOTALE_CONCORDATO';
	ELE_MACRO_MATERIALE_NETTO			= 'TOTALE_MATERIALE_NETTO';
	ELE_MACRO_MATERIALE_RICARICATO	= 'TOTALE_MATERIALE_RICARICATO';
	ELE_MACRO_MANODOPERA_TEMPO			= 'TEMPO_MANODOPERA';
	ELE_MACRO_MANODOPERA_VALORE		= 'VALORE_MANODOPERA';
	ELE_MACRO_TOTALE_GENERALE			= 'TOTALE_GENERALE';
	ELE_MACRO_VERSIONE					= 'VERSIONE';
	ELE_MACRO_VERSIONE_VERSIONE		= 'VERSIONE_VERSIONE';
	ELE_MACRO_VERSIONE_REVISIONE		= 'VERSIONE_REVISIONE';
	ELE_GCM : array[1..ELE_GCM_NUMBER] of string = (
		ELE_MACRO_CODICE,
		ELE_MACRO_DT_PROGETTO,
		ELE_MACRO_DT_SCADENZA,
		ELE_MACRO_ID_CONGELATO,
		ELE_MACRO_PROGRESSIVO,
		ELE_MACRO_DATA_INIZIO_LAVORI,
		ELE_MACRO_DATA_CONSEGNA,
		ELE_MACRO_CONDIZIONI_PAGAMENTO,
		ELE_MACRO_TOTALE_CONCORDATO,
		ELE_MACRO_MATERIALE_NETTO,
		ELE_MACRO_MATERIALE_RICARICATO,
		ELE_MACRO_MANODOPERA_TEMPO,
		ELE_MACRO_MANODOPERA_VALORE,
		ELE_MACRO_TOTALE_GENERALE,
		ELE_MACRO_VERSIONE,
		ELE_MACRO_VERSIONE_VERSIONE,
		ELE_MACRO_VERSIONE_REVISIONE);
{$endif ELE}

	// parametri per la stampa dell'INVENTARIO
	INVP_PARM_ANNO = 'PARM_ANNO';					// esercizio da stampare
	INVP_PARM_DATA_STAMPA = 'PARM_DATA_STAMPA';	// data della stampa
//	INVP_PARM_TITOLO = 'PARM_TITOLO';				// titolo generico della stampa
//	INVP_SEZIONE_RIMANENZE = 'RIMANENZE';
//	INVP_PARM_BO_PREZZI_ARKART = 'PARM_BO_PREZZI_ARKART';

	// parametri di ordinamento; uno solo dovrebbe essere 'T' (oppure nessuno, tutti 'F')
//	INVP_PARM_BO_ORDER_BY_DELTA_PREZZO = 'PARM_BO_ORDER_BY_DELTA_PREZZO';
//	INVP_PARM_BO_ORDER_BY_COSTO_UNITARIO = 'PARM_BO_ORDER_BY_COSTO_UNITARIO';
//	INVP_PARM_BO_ORDER_BY_COSTO_TOTALE = 'PARM_BO_ORDER_BY_COSTO_TOTALE';

	// -------------------------------------

	PRINT_SCADENZE_COMPOSTE = 'scadenze_composte';	// ricerca gruppi di pagamenti per valore complessivo

	// SCADENZE (eventualmente con pagamenti)
	SCP_PARM_BO_PRINT_PAGAMENTI = 'PARM_BO_PRINT_PAGAMENTI';
	SCP_GB_PAGAMENTI = 'GB_PAGAMENTI';	// sottosezione dei pagamenti

	PRINT_ANALISI_MOVIMENTI_MAGAZZINO = 'movimenti_magazzino_analisi';
	PRINT_ELENCO_MOVIMENTI_MAGAZZINO = 'movimenti_magazzino_elenco';

{$ifdef GESTIONE_RISORSE}
	REPORT_ELENCO_FUNZIONI = 'funzioni_elenco';
{$endif GESTIONE_RISORSE}

//	REPORT_OPERATORE_ELENCO = 'operatore_elenco';	*** fino 2024-09-27
	REPORT_OPERATORE_ELENCO = 'operatore-elenco-00';
	REPORT_OPERATORE_SINGOLO = 'operatore';

{$ifdef CODICI_VARIABILI}
	// stampa la distinta base generica oppure specifica per un pezzo
	REPORT_PRODUZIONE_DISTINTA_BASE_VIRTUALE = 'produzione_distinta_base_virtuale';
	REPORT_PRODUZIONE_DISTINTA_BASE_REALE = 'produzione_distinta_base_reale';
	REPORT_PRODUZIONE_DISTINTA_BASE_REALE_COSTI = 'produzione_distinta_base_reale_costi';
	REPORT_PRODUZIONE_ELENCO_PEZZI_CODICI_VARIABILI = 'produzione_codici_variabili_pz_elenco';
{$endif CODICI_VARIABILI}

{$ifdef PRODUZIONE}
	// fasi della distinta base produzione raggruppate per funzione utilizzata
	REPORT_ELENCO_FUNZIONI_FASI_REFERENZIATE = 'produzione_db_funzioni_utilizzate';
	REPORT_ELENCO_STATI_FASI_REFERENZIATE = 'produzione_db_stati_utilizzati';
//	REPORT_MAGAZZINO_SCORTA_MINIMA = 'produzione_magazzino_scorta_minima';		{$ifndef PROVA} !!!!! {$endif}
//	REPORT_PRODUZIONE_SCORTA_MINIMA = 'produzione_utilizzati_scorta_minima';	{$ifndef PROVA} !!!!! {$endif}

{	REPORT_PRODUZIONE_ORDINI = 'produzione_ordini';
	REPORT_PRODUZIONE_ARTICOLI = 'produzione_articoli';
	REPORT_PRODUZIONE_FASI = 'produzione_fasi';
	REPORT_PRODUZIONE_PEZZI = 'produzione_elementi';
	REPORT_PRODUZIONE_PEZZI_ACCORPATI = 'produzione_elementi_accorpati';
	REPORT_PRODUZIONE_FASI_ESPLOSE = 'produzione_fasi_esplose';
//	REPORT_PRODUZIONE_ERRORI = 'produzione_errori';
//	REPORT_PRODUZIONE_ERRORI_ACCORPATI = 'produzione_errori_accorpati';
//	REPORT_PRODUZIONE_IMPEGNI = 'produzione_impegni';
	REPORT_PRODUZIONE_ESECUZIONE = 'produzione_esecuzione'; }

	REPORT_FOGLIO_LAVORO_RISORSA = 'produzione_foglio_lavoro_risorsa';

	REPORT_CHECK_MATERIE_PRIME_PRODUZIONE = 'produzione_check_materie_prime';
	REPORT_PRODUZIONE_CARTA_IDENTITA = 'produzione_carta_identita';
{$endif PRODUZIONE}

{$ifdef IMPIANTI}
	REPORT_SEQUENZA_TEMPORALE = 'sequenza_temporale';
{$endif IMPIANTI}

{$ifdef NON_CONFORMITA}
	// registro Non Conformità e Azioni Correttive
	REG_NCAC_PARM_BO_FORNITORI = 'PARM_BO_FORNITORI';

	// VENDOR RATING
	VR_PARM_STR_PCONTI_WHERE = 'PARM_STR_PCONTI_WHERE';
	VR_PARM_STR_PCONTI_ORDER_BY = 'PARM_STR_PCONTI_ORDER_BY';
	VR_PARM_BO_CARICO = 'PARM_BO_CARICO';
	VR_PARM_BO_MOVIMENTATI = 'PARM_BO_MOVIMENTATI';
{$endif NON_CONFORMITA}

	DEFAULT_PRINT_REPORT_CPARTITA_DOC = 'cpartita_doc_elenco.gal';		// utile l'extension
{$ifdef SETUP}
	REPORT_IVA_DEFAULT = 'IVA_report.gal';		// utile l'extension
{$endif SETUP}

